# Generated by Django 4.2.2 on 2023-06-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Groceries', 'Groceries'), ('Food', 'Food')], max_length=32)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
