# Generated by Django 4.2.2 on 2023-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Groceries', 'Groceries'), ('Food', 'Food'), ('Others', 'Others')], help_text='Choose one of the following categories', max_length=32),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(help_text='Latitude in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(help_text='Longitude in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(help_text='Name of your shop (less than 32 characters)', max_length=32),
        ),
    ]
