# Generated by Django 4.2.2 on 2023-06-15 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops_app', '0002_alter_shop_category_alter_shop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(choices=[('Bangalore', 'Bangalore')], default='Bangalore', help_text='Choose the location of your shop', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
